spring:
  application.name: client

server.port: 8001
endpoints.health.sensitive: false  
eureka:
  client.serviceUrl.defaultZone: http://localhost:9000/eureka/
  instance.hostname: backendone
    
      
