server:
  port: 8890

spring:
  application:
    name: apiclient
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.database: poc
    mongo.repositories.enabled: true
  datasource:
    max-wait: 1000
    max-active: 100  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: false
    
      
